language: php

php:
    - 7.2

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=clover.xml
    - composer phpcs

after_success:
    - bash <(curl -s https://codecov.io/bash)
