language: php

php:
    - 7.2
    - 7.3
    - 7.4

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - php vendor/bin/phpunit --coverage-clover=clover.xml
    - php vendor/bin/phpstan analyse -l 4 src tests
    - composer phpcs

after_success:
    - bash <(curl -s https://codecov.io/bash)
