language: php

matrix:
    include:
        - php: 7.2
          dist: bionic
        - php: 7.2
          dist: bionic
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.3
          dist: bionic
        - php: 7.4
          dist: bionic

before_script:
    - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
    - php vendor/bin/phpunit --coverage-clover=clover.xml
    - php vendor/bin/phpstan analyse -l max src tests
    - composer phpcs

after_success:
    - bash <(curl -s https://codecov.io/bash)
